---
- name: Ensure libvirt LVM storage pool directories exist
  community.general.lvg:
    vg: "{{ item.source }}"
    pvs: "{{ item.pvs }}"
  when: item.type in ["lvm2", "logical"]
  loop: "{{ libvirt_host_pools | flatten(levels=1) }}"
  become: true

- name: Include rbd.yml
  ansible.builtin.include_tasks:
    file: rbd.yml
    apply:
      become: true
  when: item.type == "rbd"
  loop: "{{ libvirt_host_pools | flatten(levels=1) }}"

- name: Ensure libvirt storage pools are defined
  community.libvirt.virt_pool:
    name: "{{ item.name }}"
    command: define
    xml: "{{ item.xml | default(lookup('template', 'pool.xml.j2')) }}"
    uri: "{{ libvirt_host_uri | default(omit, true) }}"
  loop: "{{ libvirt_host_pools | flatten(levels=1) }}"
  become: true

- name: Check libvirt directory storage pool status
  community.libvirt.virt_pool:
    name: "{{ item.name }}"
    command: status
    uri: "{{ libvirt_host_uri | default(omit, true) }}"
  when: item.type == "dir"
  loop: "{{ libvirt_host_pools | flatten(levels=1) }}"
  become: true
  register: pool_status

- name: Ensure libvirt directory storage pools are built
  community.libvirt.virt_pool:
    name: "{{ item.item.name }}"
    command: build
    uri: "{{ libvirt_host_uri | default(omit, true) }}"
  when:
    - item is not skipped
    - item.status != "active"
  loop: "{{ pool_status.results }}"
  become: true

- name: Ensure libvirt storage pools are active
  community.libvirt.virt_pool:
    name: "{{ item.name }}"
    state: active
    uri: "{{ libvirt_host_uri | default(omit, true) }}"
  loop: "{{ libvirt_host_pools | flatten(levels=1) }}"
  become: true

- name: Ensure libvirt storage pools are started on boot
  community.libvirt.virt_pool:
    name: "{{ item.name }}"
    autostart: true
    uri: "{{ libvirt_host_uri | default(omit, true) }}"
  loop: "{{ libvirt_host_pools | flatten(levels=1) }}"
  become: true
