---

- name: Install additional packages for rbd support
  ansible.builtin.package:
    name: "{{ libvirt_host_packages_rbd_volume_pool | flatten(levels=1) }}"
    state: present
  notify: restart libvirt

- name: Create temporary file for Ceph secret
  ansible.builtin.tempfile:
    state: file
    suffix: .xml
  register: secret_tempfile

- name: Send Ceph secret
  ansible.builtin.template:
    src: ceph_secret.xml.j2
    dest: "{{ secret_tempfile.path }}"
    mode: "0600"

- name: Define Ceph secret
  ansible.builtin.command: "virsh secret-define {{ secret_tempfile.path }}"
  changed_when: true

- name: Set Ceph secret value
  ansible.builtin.command: "virsh secret-set-value {{ item.name | to_uuid }} {{ item.passphrase }}"
  changed_when: true

- name: Delete temporary file
  ansible.builtin.file:
    path: "{{ secret_tempfile.path }}"
    state: absent

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
